# Shader upscaling toggles
ALT+1 script-binding toggle_profiles/toggle-anime
ALT+2 script-binding toggle_profiles/toggle-fsrcnnx
ALT+0 no-osd change-list glsl-shaders clr ""; show-text "All GLSL shaders disabled"

# uosc UI
mbtn_right script-binding uosc/menu

# RIFE TensorRT interpolation toggles
ALT+r script-binding toggle_profiles/toggle-rife
ALT+9 no-osd set vf ""; no-osd set hwdec auto-safe; show-text "Video filters disabled"
