# Anime-oriented shader upscaling profile.
[anime]
glsl-shaders="~~/shaders/Anime4K/Anime4K_Clamp_Highlights.glsl;~~/shaders/Anime4K/Anime4K_Restore_CNN_VL.glsl;~~/shaders/Anime4K/Anime4K_Upscale_CNN_x2_VL.glsl;~~/shaders/Anime4K/Anime4K_AutoDownscalePre_x4.glsl"

# General-purpose FSRCNNX shader upscaling profile.
[fsrcnnx]
glsl-shaders="~~/shaders/FSRCNNX/FSRCNNX_x2_16-0-4-1.glsl"
